config/routes.rb
Rails.application.routes.draw do
  # root :to => "landing_page#index"
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  devise_for :admin_users, controllers: {registrations: "admin_users/registrations", sessions: "admin_users/sessions"}

  resources :users, only: [:update]
  resources :admin_users

  devise_scope :user do
      authenticated :user do
        get '/' =>  'devise/sessions#new', as: :authorized_user_root
        # root :to => 'students/dashboards#show', :constraints => lambda{ |req| req.session['warden.user.user.key'][0] == 'User' }
      end
      unauthenticated :user do
        get '/user/signin' =>  'devise/sessions#new', as: :unauthorized_user_root
      end
  end

  devise_scope :admin_user do
    authenticated :admin_user do
      root to: 'admin_users/dashboards#index', as: :authenticated_admin_user_root
    end
    unauthenticated :admin_user do
      get "/admin/signin" => 'devise/sessions#new', as: :unauthenticated_admin_user_root
    end
  end


  get '/admin/dashboard' => 'admin_users/dashboards#index', as: :admin_home
  get '/admin/manage_inventory' => 'admin_users/manage_inventories#index', as: :manage_inventory

  namespace :admin do
    resources :books, only:[:new,:update,:edit,:show]
  end

  root to: "landing_page#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username,:employee_id, :first_name,:last_name,:state,:city,:address,:phone, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username,:first_name,:last_name,:state,:city,:address,:phone, presence: true
end

app/controllers/AdminUser/passwords_controller.rb
# frozen_string_literal: true

class AdminUser::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/AdminUser/sessions_controller.rb
# frozen_string_literal: true

class AdminUser::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_path_for(resource)
    landing_page_index_path
  end
end

app/controllers/AdminUser/unlocks_controller.rb
# frozen_string_literal: true

class AdminUser::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin_users/books_controller.rb
class AdminUsers::BooksController < ApplicationController

  def new
  end

  def create
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  require 'users/parameter_sanitizer'
  require 'admin_users/parameter_sanitizer'

  protected
    def devise_parameter_sanitizer
      if resource_class == User
        Users::ParameterSanitizer.new(User,:user,params)
      elsif resource_class == AdminUser
        AdminUsers::ParameterSanitizer.new(AdminUser,:admin_user,params)
      else
        super
      end
    end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
  end
end

app/controllers/users/parameter_sanitizer.rb
class Users::ParameterSanitizer < Devise::ParameterSanitizer
  def initialize(*)
    super
    permit(:sign_up, keys:[:username, :email, :password, :password_confirmation, :first_name, :last_name,:state,:city,:address,:phone])
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    landing_page_index_path
  end

  def after_sign_out_path_for(resource)
    unauthorized_user_root_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_sanitizer.rb
class User::ParameterSanitizer < Devise::ParameterSanitizer
  def initialize(*)
    super
    permit(:sign_up, keys:[:username, :email, :password, :password_confirmation, :first_name, :last_name,:state,:city,:address,:phone])
  end
end

app/helpers/admin_users/books_helper.rb
module AdminUsers::BooksHelper
end

app/helpers/admin_users/dashboards_helper.rb
module AdminUsers::DashboardsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#">Digital Library</a>
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <% if current_admin_user %>
        <% if current_page?(admin_home_path)%>
          <li class="nav-item active">
            <%= link_to "Home", admin_home_path, class: "nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Home", admin_home_path, class: "nav-link"%>
          </li>
        <% end %>

        <% if current_page?(manage_inventory_path)%>
          <li class="nav-item active">
            <%= link_to "Manage Inventory", manage_inventory_path, class: "nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Manage Inventory", manage_inventory_path, class: "nav-link"%>
          </li>
        <% end %>

        <% if current_page?(admin_home_path)%>
          <li class="nav-item active">
            <%= link_to "Manage Reservations", "#", class: "nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Manage Reservations", "#", class: "nav-link"%>
          </li>
        <% end %>

        <% if current_page?(admin_home_path)%>
          <li class="nav-item active">
            <%= link_to "Registered Users", "#", class: "nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Registered Users", "#", class: "nav-link"%>
          </li>
        <% end %>

        <% if current_page?(admin_home_path)%>
          <li class="nav-item active">
            <%= link_to "My Profile", "#", class: "nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "My Profile", "#", class: "nav-link"%>
          </li>
        <% end %>

        <li class="nav-item">
          <%= link_to "Sign out", destroy_admin_user_session_path, method: :delete, class: "nav-link"%>
        </li>
      <% elsif current_user %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DigitalLibrary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div>
      <%= render "layouts/nav"%>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>